foam.POM({
  name: "crunch",
  projects: [
    { name: "crunchtest/pom", flags: "test" },
    { name: "ruler/pom"},
    { name: "test/pom", flags: "test" }
  ],
  files: [
    { name: "UserCapabilityJunctionExpiredDAO",                       flags: "java" },
    { name: "edit/EditBehaviour",                                     flags: "js|java" },
    { name: "edit/AbstractEditBehaviour",                             flags: "js|java" },
    { name: "AssociatedEntity",                                       flags: "js|java" },
    { name: "CapabilityGrantMode",                                    flags: "js|java" },
    { name: "Capability",                                             flags: "js|java" },
    { name: "Renewable",                                              flags: "js|java" },
    { name: "Refinements",                                            flags: "js|java" },
    { name: "MinMaxCapability",                                       flags: "js|java" },
    { name: "MinMaxCapabilityData",                                   flags: "js|java" },
    { name: "CapabilityJunctionStatus",                               flags: "js|java" },
    { name: "CapabilityIntercept",                                    flags: "js|java" },
    { name: "CapabilityJunctionPayload",                              flags: "js|java" },
    { name: "lite/Capable",                                           flags: "js|java" },
    { name: "lite/ReferencePayloadData",                              flags: "js|java" },
    { name: "lite/CapableDAO",                                        flags: "js|java" },
    { name: "lite/CapableAdapterDAO",                                 flags: "js|java" },
    { name: "lite/BaseCapable",                                       flags: "js|java" },
    { name: "lite/CapableObjectData",                                 flags: "js|java" },
    { name: "lite/CapableObjectDataProperties",                       flags: "js|java" },
    { name: "lite/CapableCompatibleCapability",                       flags: "js|java" },
    { name: "lite/CapabilityRefinement",                              flags: "js|java" },
    { name: "lite/MinMaxCapabilityRefinement",                        flags: "js|java" },
    { name: "lite/RequirementsRuleAction",                            flags: "js|java" },
    { name: "lite/RequirementSpec",                                   flags: "js|java" },
    { name: "crunchtest/TestCapable",                                 flags: "js&test|java&test" }, // NOTE: has to be at this pom level and listed after CapableObjectData
    { name: "CapabilityAvailabilityDAO",                              flags: "js|java" },
    { name: "example/ExampleData",                                    flags: "js|java" },
    { name: "lite/predicate/ContainsGranted",                         flags: "js|java" },
    { name: "lite/ruler/CapableStatusChangeAdjustApprovalsRuleAction",flags: "js|java" },
    { name: "lite/ruler/CapablePayloadApprovableRuleAction",          flags: "js|java" },
    { name: "lite/ruler/CapableCreateApprovalsRuleAction",            flags: "js|java" },
    { name: "lite/ruler/SetCapablePayloadStatusOnPut",                flags: "js|java" },
    { name: "lite/ruler/ReputDependantPayloads",                      flags: "js|java" },
    { name: "lite/ruler/UCJApprovableValidateAction",                 flags: "js|java" },
    { name: "CapabilityCategory",                                     flags: "js|java" },
    { name: "UserCapabilityJunctionRefine",                           flags: "js|java" },
    { name: "CapabilityCapabilityJunctionRefine",                     flags: "js|java" },
    { name: "CapabilityCategoryCapabilityJunctionRefine",             flags: "js|java" },
    { name: "UCJProperty",                                            flags: "js" },
    { name: "UCJUpdateApprovable",                                    flags: "js|java" },
    { name: "connection/CapabilityPayload",                           flags: "js|java" },
    { name: "connection/CapabilityPayloadRecord",                     flags: "js|java" },
    { name: "connection/GrantPathNode",                               flags: "js|java" },
    { name: "document/Document",                                      flags: "js|java" },
    { name: "UserCapabilityJunctionDAO",                              flags: "js|java" },
    { name: "UserCapabilityTicket",                                   flags: "js|java" },
    { name: "connection/CapabilityPayloadDAO",                        flags: "js|java" },
    { name: "PredicatedPrerequisiteCapabilityJunctionDAO",            flags: "js|java" },
    { name: "SendNotificationOnTopLevelCapabilityStatusUpdate",       flags: "js|java" },
    { name: "CrunchService",                                          flags: "js|java" },
    { name: "SessionCrunchCache",                                     flags: "js|java" },
    { name: "ClientCrunchService",                                    flags: "js" },
    { name: "ReputDependentUCJs",                                     flags: "js|java" },
    { name: "predicate/CapabilityIsStatus",                           flags: "js|java" },
    { name: "predicate/CapabilityHasBeenGranted",                     flags: "js|java" },
    { name: "predicate/CapabilityPrerequisitesGranted",               flags: "js|java" },
    { name: "predicate/StatusChangedTo",                              flags: "js|java" },
    { name: "predicate/IsAgent",                                      flags: "js|java" },
    { name: "predicate/IsSpid",                                       flags: "js|java" },
    { name: "predicate/CapabilityJunctionTransitionToStatus",         flags: "js|java" },
    { name: "predicate/IsAgentUpdate",                                flags: "js|java" },
    { name: "predicate/IsCapabilityJunctionOf",                       flags: "js|java" },
    { name: "ruler/AuthorizeUCJStatusOnPut",                          flags: "js|java" },
    { name: "ruler/CheckUCJOwnershipOnPut",                           flags: "js|java" },
    { name: "ruler/ValidateUCJDataOnPut",                             flags: "js|java" },
    { name: "ruler/SetUCJStatusOnPut",                                flags: "js|java" },
    { name: "ruler/ConfigureUCJExpiryOnGranted",                      flags: "js|java" },
    { name: "ruler/SaveUCJDataOnGranted",                             flags: "js|java" },
    { name: "ruler/InvokeEditBehaviourRuleAction",                    flags: "js|java" },
    { name: "ruler/UserCapabilityTicketRuleAction",                   flags: "js|java" },
    { name: "ui/WizardState",                                         flags: "js|java" },
    { name: "ui/ApprovableUserCapabilityJunctionWAO",                 flags: "js" },
    { name: "ui/UserCapabilityJunctionWAO",                           flags: "js" },
    { name: "ui/CapableWAO",                                          flags: "js" },
    { name: "ui/CapabilityWizardlet",                                 flags: "js|java" },
    { name: "ui/ReloadSubjectWizardlet",                              flags: "js" },
    { name: "ui/MinMaxCapabilityWizardlet",                           flags: "js|java" },
    { name: "ui/MinMaxCapabilityWizardletSection",                    flags: "js" },
    { name: "ui/ReviewCapabilityWizardlet",                           flags: "js|java" },
    { name: "ui/ReviewCapabilityView",                                flags: "js" },
    { name: "ui/ReviewUCJView",                                       flags: "js" },
    { name: "ui/CapableView",                                         flags: "js" },
    { name: "ui/CapablePayloadROView",                                flags: "js" },
    { name: "ui/UCJView",                                             flags: "js" },
    { name: "ui/PrerequisiteAwareWizardlet",                          flags: "js|java" },
    { name: "ui/LiftingAwareWizardlet",                               flags: "js|java" },
    { name: "box/CrunchClientBox",                                    flags: "js|java" },
    { name: "box/CrunchClientReplyBox",                               flags: "js|java" },
    { name: "extra/ReviewCapability",                                 flags: "js|java" },
    { name: "extra/ReviewCapabilityData",                             flags: "js|java" },
    { name: "extra/ReviewWizard",                                     flags: "js|java" },
    { name: "extra/ImplyReviewedAction",                              flags: "js|java" },
    { name: "test/CrunchTestSupport",                                 flags: "js&test" },
    { name: "sandbox/CapabilityEditIntention",                        flags: "js|java" },
    { name: "edit/NullEditBehaviour",                                 flags: "js|java" },
    { name: "edit/PermissiveEditBehaviour",                           flags: "js|java" },
    { name: "edit/PredicatedEditBehaviour",                           flags: "js|java" },
    { name: "edit/ApprovalEditBehaviour",                             flags: "js|java" },
    { name: "TopLevelCapabilityStatusUpdateNotification",             flags: "js|java" }
  ],

  javaFiles: [
    { name: "UserCapabilityUpdateInterceptDAO" },
    { name: "ExpireUserCapabilityJunctionsCron" },
    { name: "ServerCrunchService" }
  ]
});
