foam.POM({
  name: 'console',
  files: [
    { name: '../../u2/mlang/Table',    flags: 'js|java' },
    { name: 'SinkView',                flags: 'js' },
    { name: 'PropertyChoiceView',      flags: 'js' },
    { name: 'PropertyListView',        flags: 'js' },
    { name: 'PropertyOrderChoiceView', flags: 'js' },
    { name: 'Console',                 flags: 'js' },
    { name: 'DAOCreate',               flags: 'js' },
    { name: 'AbstractDAOAgent',        flags: 'js' },
    { name: 'CellsSink',               flags: 'js|java' },
    { name: 'CitationSink',            flags: 'js|java' },
    { name: 'JSONSink',                flags: 'js|java' },
    { name: 'XMLSink',                 flags: 'js|java' },
    { name: 'ViewSink',                flags: 'js|java' },
    { name: 'EditSink',                flags: 'js|java' },
    { name: 'GridBy',                  flags: 'js|java' },
    { name: 'DuplicateSink',           flags: 'js|java' },
    { name: 'DAOPrompt',               flags: 'js' },
    { name: 'UploadAgent',             flags: 'js|java' },
    { name: 'Upload',                  flags: 'js' },
    { name: 'ModelDAO',                flags: 'js' },
    { name: 'DocumentReadWriteView',   flags: 'js' },
    { name: 'ConsoleZACClient',        flags: 'js' },
    { name: 'Flow',                    flags: 'js|java' },
    { name: 'ReactiveDetailView',      flags: 'js' },
    { name: 'Script',                  flags: 'js' },
    { name: 'XHR',                     flags: 'js' },
    { name: 'Check',                   flags: 'js' },
    { name: 'Signature',               flags: 'js' },
    { name: 'Header',                  flags: 'js' },
    { name: 'Doc',                     flags: 'js' },
    { name: 'cmd/Commands',            flags: 'js|java' }
  ]
});
