foam.POM({
  name: "ruler",
  projects: [
    { name: 'predicate/pom' }
  ],
  files: [
    { name: "Rule",                                                    flags: "js|java" },
    { name: "RuleGroup",                                               flags: "js|java" },
    { name: "Ruled",                                                   flags: "js|java" },
    { name: "FindRuledCommand",                                        flags: "js|java" },
    { name: "PermissionedUserRule",                                    flags: "js|java" },
    { name: "PermissionedSubjectRule",                                 flags: "js|java" },
    { name: "PermissionedUCJRule",                                     flags: "js|java" },
    { name: "RuleAction",                                              flags: "js|java" },
    { name: "RulePredicate",                                           flags: "js|java" },
    { name: "RuleActionMergeDecorator",                                flags: "js|java" },
    { name: "CompositeRuleAction",                                     flags: "js|java" },
    { name: "StopRulerAction",                                         flags: "js|java" },
    { name: "RuleHistory",                                             flags: "js|java" },
    { name: "RuleHistoryStatus",                                       flags: "js|java" },
    { name: "RuledDAO",                                                flags: "js|java" },
    { name: "RulerDAO",                                                flags: "js|java" },
    { name: "RulerData",                                               flags: "js|java" },
    { name: "ScriptPredicate",                                         flags: "js|java" },
    { name: "UpdateRulesListSink",                                     flags: "js|java" },
    { name: "TestedRule",                                              flags: "js|java" },
    { name: "RulerProbe",                                              flags: "js|java" },
    { name: "Relationships",                                           flags: "js" },
    { name: "action/AbstractCheckDAOforMatching",                      flags: "js|java" },
    { name: "action/ChangePropertyAction",                             flags: "js|java" },
    { name: "action/DAOPutRuleAction",                                 flags: "js|java" },
    { name: "action/SendNotification",                                 flags: "js|java" },
    { name: "action/JShellRuleAction",                                 flags: "js|java" },
    { name: "predicate/PropertyChangePredicate",                       flags: "js|java" },
    { name: "predicate/PropertyEQProperty",                            flags: "js|java" },
    { name: "predicate/PropertyHasValue",                              flags: "js|java" },
    { name: "predicate/PropertyEQValue",                               flags: "js|java" },
    { name: "predicate/PropertyNEQValue",                              flags: "js|java" },
    { name: "predicate/NewEqOld",                                      flags: "js|java" },
    { name: "predicate/PropertyIsInstance",                            flags: "js|java" },
    { name: "predicate/PropertyIsClass",                               flags: "js|java" },
    { name: "predicate/ContextContainsPredicate",                      flags: "js|java" },
    { name: "predicate/FScriptRulePredicate",                          flags: "js|java" },
    { name: "predicate/PropertyIsSetPredicate",                        flags: "js|java" },
    { name: "predicate/ApprovalReputPredicate",                        flags: "js|java" },
    { name: "test/RuledDAOTest",                                       flags: "js&test|java&test" },
    { name: "test/RuledDummy",                                         flags: "js&test|java&test" }
  ],
  javaFiles: [
    { name: "RuleEngine" },
    { name: "RetryManager" },
    { name: "cron/RenewRuleHistoryCron" },
    { name: "test/DummyErroneousPredicate",                            flags: "test" },
    { name: "test/RulerDAOTest",                                       flags: "test" }
  ]
});
