/**
 * @license
 * Copyright 2023 The FOAM Authors. All Rights Reserved.
 * http://www.apache.org/licenses/LICENSE-2.0
 */

exports.description = 'copies .jrl files into /build/journals';

const fs_   = require('fs');
const path_ = require('path');
const b_    = require('./buildlib');
const rl_   = require('readline');

const journalFiles  = [];
const journalOutput = {};
const imageDirs     = [ 'images' ];

function addJournalOutput(j, o) {
  if ( ! journalOutput[j] ) journalOutput[j] = [];
  journalOutput[j].push(o);
}

exports.init = function() {
  X.journaldir = X.builddir + '/journals/';
  b_.emptyDir(X.journaldir);
}


exports.visitFile = async function(pom, f, fn) {
  if ( f.name.endsWith('.jrl') ) {
    // Disallow wildcard matching for excluding .jrl files, excluded entries must be exact match
//    if ( b_.isExcluded(pom, fn, true) ) return;

    verbose('\t\tjournal source:', fn);
    journalFiles.push(fn);

    var i           = fn.lastIndexOf('/');
    var journalName = fn.substring(i+1, fn.length-4);

    addJournalOutput(journalName, {
      fn: fn,
      msg: `// The following lines were copied from "${path_.relative(process.cwd(), fn)}"\n`
    });
  }
}


exports.visitDir = function(pom, f, fn) {
  if ( f.name === 'images' || f.name === 'favicon' ) {
    imageDirs.push(fn);
  }
}


exports.end = function() {
  console.log(`[Journal Maker] Creating journals to ${X.journaldir} from ${X.pom}`);

  if ( X.pom !== 'pom' ) {
    var poms = X.pom.split(',').map(f => path_.relative(process.cwd(), f)).join(',');
    console.log(`[Journal Maker] Setting POM to ${poms}`);

    addJournalOutput('services', `
// The following record was generated by JournalMaker

p({
  "class":"foam.core.boot.CSpec",
  "name":"appConfig",
  "service": {
    "class":"foam.core.app.AppConfig",
    "pom":"${poms}"
  }
})
`);
  }

  if ( imageDirs.length > 1 ) {
    var paths = imageDirs.map(f => path_.relative(process.cwd(), f)).join(':');
    addJournalOutput('services', `
// The following record was generated by JournalMaker

p({
  "class":"foam.core.boot.CSpec",
  "name":"http",
  "service": {
    "class":"foam.core.jetty.HttpServer",
    "imageDirs":"${paths}"
  }
})
`);
  }

  function error(err) {
    if ( err ) console.error('Error appending to file:', err);
  }

  async function appendFile(ws, fn) {
    return new Promise(function(res, rej) {
      const rs = fs_.createReadStream(fn);
      const rl = rl_.createInterface({input: rs, crlfDelay: Infinity});

      rl.on('close', function() {
        res('');
      });
      rl.on('line', function (line) {
        ws.write(line + '\n');
      });
    });
  }

  (async function() {
    var keys = Object.keys(journalOutput);
    for ( var i = 0 ; i < keys.length ; i++ ) {
      const f           = keys[i];
      const fn          = X.journaldir + f + '.0';
      const writeStream = fs_.createWriteStream(fn, { });
      const a           = journalOutput[f];

      for ( var j = 0 ; j < a.length ; j++ ) {
        var o = a[j];
        if ( typeof o === 'string' ) {
          await writeStream.write(o + '\n', error);
        } else {
          await writeStream.write(o.msg + '\n', error);
          await appendFile(writeStream, o.fn);
          await writeStream.write('\n', error);
        }
      }
      writeStream.close();
    }
  })();

  console.log(`[Journal Maker] Generating ${Object.keys(journalOutput).length} journal files from ${journalFiles.length} sources.`);
}
