/**
 * @license
 * Copyright 2023 The FOAM Authors. All Rights Reserved.
 * http://www.apache.org/licenses/LICENSE-2.0
 */

exports.description = 'Concatenate all repository .jrl files into .0 files.';

const fs_   = require('fs');
const path_ = require('path');

const journalFiles  = [];
const journalOutput = {};
const imageDirs     = [ 'images' ];

function addJournalOutput(j, o) {
  if ( ! journalOutput[j] ) journalOutput[j] = [];
  journalOutput[j].push(o);
}

exports.init = function() {
  X.journaldir = X.journaldir || (X.builddir + '/journals');
  this.emptyDir(X.journaldir);

  flags.loadFiles = true;
}

exports.visitFile = function(pom, f, fn) {
  if ( f.name.endsWith('.jrl') ) {
    var i           = fn.lastIndexOf('/');
    var journalName = fn.substring(i+1, fn.length-4);

    // Disallow wildcard matching for excluding .jrl files, excluded entries must be exact match
    // if ( isExcluded(pom, fn, true) ) return;

    // Until all journal files are under pom control, use the
    // journalFiles list as an exclude list.
    // If test flag enabled - include if present and flag match
    if ( ! flags.test && pom.journalFiles ) {
      // journalFiles name is relative to pom
      var name = f.parentPath ? f.parentPath.substring(pom.location.length+1) : '';
      name += (name ? '/' : '') + journalName;
      let jf = pom.journalFiles.find((jf) => jf.name === name);
      if ( jf && foam.checkForFlag(foam.adaptFlags(jf.flags), 'test') )
        return;
    }
    if ( f.name.endsWith('tests.jrl') && ! flags.test )
      return;

    this.verbose('\t\tjournal source:', fn);
    journalFiles.push(fn);

    addJournalOutput(journalName, {
      fn: fn,
      msg: `// The following lines were copied from "${path_.relative(process.cwd(), fn)}"\n`
    });
  }
}


exports.visitDir = function(pom, f, fn) {
  if ( f.name === 'images' || f.name === 'favicon' ) {
    imageDirs.push(fn);
  }
}


exports.end = function() {
  this.verbose(`[Journal Maker] Creating journals to ${X.journaldir} from ${X.pom}`);

  if ( X.pom !== 'pom' ) {
    var poms = X.pom.split(',').map(f => path_.relative(process.cwd(), f)).join(',');
    var flgs = '';
    Object.keys(flags).forEach(key => {
      // this.info(`[Journal] flags[${key}]:${flags[key]}`);
      if ( key.startsWith('-') ||
           flags[key] === true ) {
        flgs = this.comma(flgs, key);
      }
    });
    this.info(`[Journal] flags:${flgs}`);

    addJournalOutput('services', `
// The following record was generated by JournalMaker

p({
  "class":"foam.core.boot.CSpec",
  "name":"appConfig",
  "service": {
    "class":"foam.core.app.AppConfig",
    "pom":"${poms}",
    "flags":"${flgs}"
  }
})
`);
  }

  if ( imageDirs.length > 1 ) {
    var paths = imageDirs.map(f => path_.relative(process.cwd(), f)).join(':');
    addJournalOutput('services', `
// The following record was generated by JournalMaker

p({
  "class":"foam.core.boot.CSpec",
  "name":"http",
  "service": {
    "class":"foam.core.jetty.HttpServer",
    "imageDirs":"${paths}"
  }
})
`);
  }

  var keys = Object.keys(journalOutput);
  for ( var i = 0 ; i < keys.length ; i++ ) {
    const f           = keys[i];
    const fn          = X.journaldir + '/' + f + '.0';
    const writeStream = fs_.openSync(fn, 'w');
    const a           = journalOutput[f];
    this.verbose('[Journal] creating', fn);
    for ( var j = 0 ; j < a.length ; j++ ) {
      var o = a[j];
      try {
        if ( typeof o === 'string' ) {
          fs_.writeSync(writeStream, o + '\n');
        } else {
          fs_.writeSync(writeStream, o.msg + '\n');
          fs_.writeSync(writeStream, fs_.readFileSync(o.fn));
          fs_.writeSync(writeStream, '\n');
        }
      } catch(e) {
        this.error(e);
      }
    }
  }

  this.log(`[Journal Maker] Generating ${Object.keys(journalOutput).length} journal files from ${journalFiles.length} sources.`);
};
